name: Pull Request Title

on:
  pull_request_target:
    types: ['opened', 'reopened', 'edited', 'synchronize']

permissions:
  pull-requests: read

jobs:
  faency:
    name: Lint PR Title
    runs-on: ubuntu-latest

    steps:
      - name: Semantic pull request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: amannn/action-semantic-pull-request@v5
